### HTTP Request Definitions

@baseUrl = http://localhost:3000/api
@contentType = application/json

### Create Admin
POST {{baseUrl}}/user/signup
Content-Type: {{contentType}}

{
  "name": "Admin User 5",
  "email": "admin5@example.com",
  "password": "securePassword123",
  "role": "admin"
}

### Create Designer
POST {{baseUrl}}/user/signup
Content-Type: {{contentType}}

{
  "name": "Designer34 ",
  "email": "designer5@example.com",
  "password": "securePassword123",
  "role": "designer"
}

### Create Source Manager
POST {{baseUrl}}/user/signin
Content-Type: {{contentType}}

{
  "name": "John Doe",
  "email": "john.doe@techinnovations.com",
  "password": "smPassword123",
  "role": "sourceManager",
}
### Create Source Manager
POST {{baseUrl}}/user/createCompany
Content-Type: {{contentType}}

{
  "companyName": "Tech Innovations",
  "email": "contact@techinnovations.com",
  "password": "companyPassword123",
  "role": "CompanyAdmin",
  "sourceManagers": [
    {
      "name": "John Doe",
      "email": "john.doe@techinnovations.com",
      "password": "smPassword123",
      "role": "SourceManager"
    },
    {
      "name": "Jane Smith",
      "email": "jane.smith@techinnovations.com",
      "password": "smPassword456",
      "role": "SourceManager"
    }
  ]
}


### Sign In
POST {{baseUrl}}/signin
Content-Type: {{contentType}}

{
  "email": "admin@example.com",
  "password": "securePassword123",
  "role": "sourceManager"
}
